tap "homebrew/cask-fonts"

brew "ack"
brew "htop"
brew "neovim"
brew "pwgen"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "iterm2"
cask "basictex"
cask "deckset"
cask "flux"
cask "font-jetbrains-mono"
cask "grammarly-desktop"
cask "rocket"
cask "skype"
cask "spotify"
cask "vlc"
