brew "bat"
brew "fzf"
brew "rg"
brew "htop"
brew "neofetch"
brew "neovim"
brew "pwgen"
brew "wget"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "1password"
cask "basictex"
cask "deckset"
cask "fliqlo"
cask "ghostty"
cask "grammarly-desktop"
cask "rocket"
cask "spotify"

cask "font-caveat"
cask "font-caveat-brush"
cask "font-courgette"
cask "font-jetbrains-mono"
cask "font-monoton"
cask "font-neucha"
cask "font-sigmar-one"
